//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 05:23:08 PM CST 
//


package com.hotent.bpmx.core.defxml.entity.hotent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotent.bpmx.core.defxml.entity.hotent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExecutionPlugin_QNAME = new QName("http://www.jee-soft.cn/bpmnx/plugin", "executionPlugin");
    private final static QName _TaskPlugin_QNAME = new QName("http://www.jee-soft.cn/bpmnx/plugin", "taskPlugin");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotent.bpmx.core.defxml.entity.hotent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExecutionPlugin }
     * 
     */
    public ExecutionPlugin createExecutionPlugin() {
        return new ExecutionPlugin();
    }

    /**
     * Create an instance of {@link TaskPlugin }
     * 
     */
    public TaskPlugin createTaskPlugin() {
        return new TaskPlugin();
    }

    /**
     * Create an instance of {@link PluginDef }
     * 
     */
    public PluginDef createPluginDef() {
        return new PluginDef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionPlugin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jee-soft.cn/bpmnx/plugin", name = "executionPlugin")
    public JAXBElement<ExecutionPlugin> createExecutionPlugin(ExecutionPlugin value) {
        return new JAXBElement<ExecutionPlugin>(_ExecutionPlugin_QNAME, ExecutionPlugin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskPlugin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jee-soft.cn/bpmnx/plugin", name = "taskPlugin")
    public JAXBElement<TaskPlugin> createTaskPlugin(TaskPlugin value) {
        return new JAXBElement<TaskPlugin>(_TaskPlugin_QNAME, TaskPlugin.class, null, value);
    }

}
