//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.24 at 05:23:08 PM CST 
//


package com.hotent.bpmx.core.defxml.entity.hotent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for taskPlugin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="taskPlugin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plugin-def" type="{http://www.jee-soft.cn/bpmnx/plugin}plugin-def"/>
 *       &lt;/sequence>
 *       &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taskPlugin", propOrder = {
    "pluginDef"
})
public class TaskPlugin {

    @XmlElement(name = "plugin-def", required = true)
    protected PluginDef pluginDef;
    @XmlAttribute(name = "event", required = true)
    protected String event;
    @XmlAttribute(name = "class", required = true)
    protected String clazz;

    /**
     * Gets the value of the pluginDef property.
     * 
     * @return
     *     possible object is
     *     {@link PluginDef }
     *     
     */
    public PluginDef getPluginDef() {
        return pluginDef;
    }

    /**
     * Sets the value of the pluginDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginDef }
     *     
     */
    public void setPluginDef(PluginDef value) {
        this.pluginDef = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

}
