package com.hotent.org.persistence.query;

import java.util.ArrayList;
import java.util.List;

public class DimensionRelationQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public DimensionRelationQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDimIdIsNull() {
            addCriterion("dim_id_ is null");
            return (Criteria) this;
        }

        public Criteria andDimIdIsNotNull() {
            addCriterion("dim_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andDimIdEqualTo(String value) {
            addCriterion("dim_id_ =", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdNotEqualTo(String value) {
            addCriterion("dim_id_ <>", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdGreaterThan(String value) {
            addCriterion("dim_id_ >", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdGreaterThanOrEqualTo(String value) {
            addCriterion("dim_id_ >=", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdLessThan(String value) {
            addCriterion("dim_id_ <", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdLessThanOrEqualTo(String value) {
            addCriterion("dim_id_ <=", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdLike(String value) {
            addCriterion("dim_id_ like", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdNotLike(String value) {
            addCriterion("dim_id_ not like", value, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdIn(List<String> values) {
            addCriterion("dim_id_ in", values, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdNotIn(List<String> values) {
            addCriterion("dim_id_ not in", values, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdBetween(String value1, String value2) {
            addCriterion("dim_id_ between", value1, value2, "dimId");
            return (Criteria) this;
        }

        public Criteria andDimIdNotBetween(String value1, String value2) {
            addCriterion("dim_id_ not between", value1, value2, "dimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIsNull() {
            addCriterion("rel_dim_id_ is null");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIsNotNull() {
            addCriterion("rel_dim_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelDimIdEqualTo(String value) {
            addCriterion("rel_dim_id_ =", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotEqualTo(String value) {
            addCriterion("rel_dim_id_ <>", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdGreaterThan(String value) {
            addCriterion("rel_dim_id_ >", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdGreaterThanOrEqualTo(String value) {
            addCriterion("rel_dim_id_ >=", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLessThan(String value) {
            addCriterion("rel_dim_id_ <", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLessThanOrEqualTo(String value) {
            addCriterion("rel_dim_id_ <=", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLike(String value) {
            addCriterion("rel_dim_id_ like", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotLike(String value) {
            addCriterion("rel_dim_id_ not like", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIn(List<String> values) {
            addCriterion("rel_dim_id_ in", values, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotIn(List<String> values) {
            addCriterion("rel_dim_id_ not in", values, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdBetween(String value1, String value2) {
            addCriterion("rel_dim_id_ between", value1, value2, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotBetween(String value1, String value2) {
            addCriterion("rel_dim_id_ not between", value1, value2, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIsNull() {
            addCriterion("rel_type_ is null");
            return (Criteria) this;
        }

        public Criteria andRelTypeIsNotNull() {
            addCriterion("rel_type_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelTypeEqualTo(String value) {
            addCriterion("rel_type_ =", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeNotEqualTo(String value) {
            addCriterion("rel_type_ <>", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeGreaterThan(String value) {
            addCriterion("rel_type_ >", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rel_type_ >=", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeLessThan(String value) {
            addCriterion("rel_type_ <", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeLessThanOrEqualTo(String value) {
            addCriterion("rel_type_ <=", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeLike(String value) {
            addCriterion("rel_type_ like", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeNotLike(String value) {
            addCriterion("rel_type_ not like", value, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeIn(List<String> values) {
            addCriterion("rel_type_ in", values, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeNotIn(List<String> values) {
            addCriterion("rel_type_ not in", values, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeBetween(String value1, String value2) {
            addCriterion("rel_type_ between", value1, value2, "relType");
            return (Criteria) this;
        }

        public Criteria andRelTypeNotBetween(String value1, String value2) {
            addCriterion("rel_type_ not between", value1, value2, "relType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_dim_rel
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 13 16:44:40 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_dim_rel
     *
     * @mbggenerated Thu Feb 13 16:44:40 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}