package com.hotent.org.persistence.query;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GroupRelationQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public GroupRelationQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdIsNull() {
            addCriterion("rel_type_id_ is null");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdIsNotNull() {
            addCriterion("rel_type_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdEqualTo(String value) {
            addCriterion("rel_type_id_ =", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdNotEqualTo(String value) {
            addCriterion("rel_type_id_ <>", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdGreaterThan(String value) {
            addCriterion("rel_type_id_ >", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("rel_type_id_ >=", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdLessThan(String value) {
            addCriterion("rel_type_id_ <", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdLessThanOrEqualTo(String value) {
            addCriterion("rel_type_id_ <=", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdLike(String value) {
            addCriterion("rel_type_id_ like", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdNotLike(String value) {
            addCriterion("rel_type_id_ not like", value, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdIn(List<String> values) {
            addCriterion("rel_type_id_ in", values, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdNotIn(List<String> values) {
            addCriterion("rel_type_id_ not in", values, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdBetween(String value1, String value2) {
            addCriterion("rel_type_id_ between", value1, value2, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andRelTypeIdNotBetween(String value1, String value2) {
            addCriterion("rel_type_id_ not between", value1, value2, "relTypeId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id_ is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id_ =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id_ <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id_ >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id_ >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id_ <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id_ <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id_ like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id_ not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id_ in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id_ not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id_ between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id_ not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdIsNull() {
            addCriterion("rel_group_id_ is null");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdIsNotNull() {
            addCriterion("rel_group_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdEqualTo(String value) {
            addCriterion("rel_group_id_ =", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdNotEqualTo(String value) {
            addCriterion("rel_group_id_ <>", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdGreaterThan(String value) {
            addCriterion("rel_group_id_ >", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("rel_group_id_ >=", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdLessThan(String value) {
            addCriterion("rel_group_id_ <", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdLessThanOrEqualTo(String value) {
            addCriterion("rel_group_id_ <=", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdLike(String value) {
            addCriterion("rel_group_id_ like", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdNotLike(String value) {
            addCriterion("rel_group_id_ not like", value, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdIn(List<String> values) {
            addCriterion("rel_group_id_ in", values, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdNotIn(List<String> values) {
            addCriterion("rel_group_id_ not in", values, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdBetween(String value1, String value2) {
            addCriterion("rel_group_id_ between", value1, value2, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andRelGroupIdNotBetween(String value1, String value2) {
            addCriterion("rel_group_id_ not between", value1, value2, "relGroupId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdIsNull() {
            addCriterion("current_dim_id_ is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdIsNotNull() {
            addCriterion("current_dim_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdEqualTo(String value) {
            addCriterion("current_dim_id_ =", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdNotEqualTo(String value) {
            addCriterion("current_dim_id_ <>", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdGreaterThan(String value) {
            addCriterion("current_dim_id_ >", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdGreaterThanOrEqualTo(String value) {
            addCriterion("current_dim_id_ >=", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdLessThan(String value) {
            addCriterion("current_dim_id_ <", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdLessThanOrEqualTo(String value) {
            addCriterion("current_dim_id_ <=", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdLike(String value) {
            addCriterion("current_dim_id_ like", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdNotLike(String value) {
            addCriterion("current_dim_id_ not like", value, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdIn(List<String> values) {
            addCriterion("current_dim_id_ in", values, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdNotIn(List<String> values) {
            addCriterion("current_dim_id_ not in", values, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdBetween(String value1, String value2) {
            addCriterion("current_dim_id_ between", value1, value2, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andCurrentDimIdNotBetween(String value1, String value2) {
            addCriterion("current_dim_id_ not between", value1, value2, "currentDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIsNull() {
            addCriterion("rel_dim_id_ is null");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIsNotNull() {
            addCriterion("rel_dim_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelDimIdEqualTo(String value) {
            addCriterion("rel_dim_id_ =", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotEqualTo(String value) {
            addCriterion("rel_dim_id_ <>", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdGreaterThan(String value) {
            addCriterion("rel_dim_id_ >", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdGreaterThanOrEqualTo(String value) {
            addCriterion("rel_dim_id_ >=", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLessThan(String value) {
            addCriterion("rel_dim_id_ <", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLessThanOrEqualTo(String value) {
            addCriterion("rel_dim_id_ <=", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdLike(String value) {
            addCriterion("rel_dim_id_ like", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotLike(String value) {
            addCriterion("rel_dim_id_ not like", value, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdIn(List<String> values) {
            addCriterion("rel_dim_id_ in", values, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotIn(List<String> values) {
            addCriterion("rel_dim_id_ not in", values, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdBetween(String value1, String value2) {
            addCriterion("rel_dim_id_ between", value1, value2, "relDimId");
            return (Criteria) this;
        }

        public Criteria andRelDimIdNotBetween(String value1, String value2) {
            addCriterion("rel_dim_id_ not between", value1, value2, "relDimId");
            return (Criteria) this;
        }

        public Criteria andIsCombinationIsNull() {
            addCriterion("is_combination_ is null");
            return (Criteria) this;
        }

        public Criteria andIsCombinationIsNotNull() {
            addCriterion("is_combination_ is not null");
            return (Criteria) this;
        }

        public Criteria andIsCombinationEqualTo(String value) {
            addCriterion("is_combination_ =", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationNotEqualTo(String value) {
            addCriterion("is_combination_ <>", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationGreaterThan(String value) {
            addCriterion("is_combination_ >", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationGreaterThanOrEqualTo(String value) {
            addCriterion("is_combination_ >=", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationLessThan(String value) {
            addCriterion("is_combination_ <", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationLessThanOrEqualTo(String value) {
            addCriterion("is_combination_ <=", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationLike(String value) {
            addCriterion("is_combination_ like", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationNotLike(String value) {
            addCriterion("is_combination_ not like", value, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationIn(List<String> values) {
            addCriterion("is_combination_ in", values, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationNotIn(List<String> values) {
            addCriterion("is_combination_ not in", values, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationBetween(String value1, String value2) {
            addCriterion("is_combination_ between", value1, value2, "isCombination");
            return (Criteria) this;
        }

        public Criteria andIsCombinationNotBetween(String value1, String value2) {
            addCriterion("is_combination_ not between", value1, value2, "isCombination");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status_ is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status_ is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status_ =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status_ <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status_ >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status_ >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status_ <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status_ <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status_ like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status_ not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status_ in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status_ not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status_ between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status_ not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time_ is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time_ =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time_ <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time_ >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time_ >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time_ <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time_ <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time_ in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time_ not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time_ between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time_ not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time_ is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time_ =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time_ <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time_ >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time_ >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time_ <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time_ <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time_ in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time_ not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time_ between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time_ not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by_ =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by_ <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by_ >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by_ >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by_ <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by_ <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by_ like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by_ not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by_ in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by_ not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by_ between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by_ not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time_ =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time_ <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time_ >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time_ >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time_ <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time_ <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time_ in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time_ not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time_ between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time_ not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by_ =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by_ <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by_ >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by_ >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by_ <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by_ <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by_ like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by_ not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by_ in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by_ not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by_ between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by_ not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time_ =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time_ <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time_ >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time_ >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time_ <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time_ <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time_ in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time_ not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time_ between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time_ not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_group_rel
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 14 09:38:13 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xog_group_rel
     *
     * @mbggenerated Fri Feb 14 09:38:13 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}